name: Deploy Helm Chart to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Import Helm Charts to ACR
        run: |
          az acr helm repo add --name reference --url https://reference.azurecr.io
          az acr helm repo add --name instance --url https://instance.azurecr.io
          helm repo update
          for chart in $(helm search repo reference | grep -v NAME | awk '{print $1}'); do
            helm fetch $chart --version 0.1.0
            helm push $chart https://instance.azurecr.io/helm/v1/repo
          done

      - name: Deploy Helm Chart to AKS
        run: |
          az aks get-credentials --resource-group  --name myResourceGroup --name myAKSClusster
          helm repo add instance https://instance.azurecr.io/helm/v1/repo
          helm repo update
          helm upgrade --install ping-app-release instance/ping-appp --namespace default --version 0.1.0 --set key1=value1,key2=value2
